version: '3.8'

services:
  frontend:
    image: node
    container_name: frontend
    ports:
      - 5173:5173
    working_dir: /app/react-app
    volumes:
      - ./:/app/react-app
    tty: true
    command: sh -c "npm install && npm run dev"
  